global:
  c4ghPath: c4gh
  jwtPath: jwt
  tlsPath: tls
  podSecurityPolicy:
    create: false
  archive:
    storageType: s3
    s3Url: "https://minio"
    s3Bucket: "archive"
    s3CaFile: "ca.crt"
    s3AccessKey: idDQBxLpXoM8l88l
    s3SecretKey: ABd6XCIvNWj7JULbrqBf8tB7q9BoHJSc
  auth:
    elixirID: DfCieZLuBU
    elixirSecret: DfCieZLuBU
    jwtSecret: oidc
    jwtAlg: ES256
    jwtKey: jwt.key
    jwtPub: jwt.pub
  backupArchive:
    storageType: s3
    s3Url: "https://minio"
    s3Bucket: "backup"
    s3CaFile: "ca.crt"
    s3AccessKey: idDQBxLpXoM8l88l
    s3SecretKey: ABd6XCIvNWj7JULbrqBf8tB7q9BoHJSc
  broker:
    host: "broker-sda-mq"
    exchange: "sda"
    port: 5671
    verifyPeer: true
    password: "admin"
    username: "admin"
    backupRoutingKey: "backup"
  cega:
    host: "cega-users"
    user: "legatest"
    password: 3iSGc5loLN7hu2EwT2Z2CzCT26iUrk3t
  db:
    host: "postgres-sda-db"
    sslMode: "verify-full"
  c4gh:
    secretName: c4gh
    keyFile: c4gh.sec.pem
    publicFile: c4gh.sec.pub
  elixir:
    provider: "http://oidc-server:8080"
    jwkPath: ""
  inbox:
    storageType: s3
    # existingClaim: test
    s3Url: "https://minio"
    s3Bucket: "inbox"
    s3AccessKey: idDQBxLpXoM8l88l
    s3SecretKey: ABd6XCIvNWj7JULbrqBf8tB7q9BoHJSc
    s3CaFile: ca.crt
    s3ReadyPath: "/minio/health/ready"
  ingress:
    deploy: false
    hostName:
      auth: sda-sda-svc-auth
      download: sda-sda-svc-download
      s3Inbox: sda-sda-svc-inbox
  logLevel: debug
  tls:
    enabled: true
auth:
  replicaCount: 1
  tls:
    secretName: "auth-certs"
backup:
  deploy: true
  tls:
    secretName: "backup-certs"
doa:
  replicaCount: 1
  tls:
    secretName: "doa-certs"
finalize:
  tls:
    secretName: "finalize-certs"
ingest:
  tls:
    secretName: "ingest-certs"
intercept:
  tls:
    secretName: "intercept-certs"
mapper:
  tls:
    secretName: "mapper-certs"
s3Inbox:
  replicaCount: 1
  tls:
    secretName: "inbox-certs"
verify:
  tls:
    secretName: "verify-certs"
download:
  replicaCount: 1
  tls:
    secretName: "download-certs"
releasetest:
  run: true
  tls:
    secretName: "tester-certs"
