apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}
data:
  pgInPasswd: {{ include "pgInPassword" . | b64enc }}
  pgOutPasswd: {{ include "pgOutPassword" . | b64enc }}
{{- if .Values.postgresAdminPassword }}
  postgresPassword: {{ .Values.postgresAdminPassword | b64enc }}
{{- end }}
