name: standalone sda deployment without TLS

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Install kube dependencies
      run: bash ./dev_tools/scripts/install-kube-deps.sh
    - name: Initialise k3d
      run: bash ./dev_tools/scripts/init-k3d.sh
    - name: Wait for k3d to become ready
      run: bash ./dev_tools/scripts/wait-for-pods.sh metrics-server k8s-app kube-system
    - name: Install sda dependencies
      run: bash ./dev_tools/scripts/install-sda-deps.sh
    - name: Create certificates
      run: bash ./dev_tools/scripts/make-certs.sh
    - name: Create secrets
      run: bash ./dev_tools/scripts/create-secrets.sh
    - name: Deploy SDA database
      run: bash ./dev_tools/scripts/sda/deploy-no-tls.sh database
    - name: Deploy SDA message broker
      run: bash ./dev_tools/scripts/sda/deploy-no-tls.sh broker
    - name: Deploy SDA orchestrator
      run: bash ./dev_tools/scripts/sda/deploy-no-tls.sh orchestrate
    - name: Deploy mock oidc server
      run: bash ./dev_tools/scripts/deploy-oidc.sh
    - name: Deploy minio
      run: bash ./dev_tools/scripts/sda/deploy-no-tls.sh minio
    - name: Create s3 buckets
      run: bash ./dev_tools/scripts/create-s3-buckets-no-tls.sh
    - name: Deploy the SDA stack
      run: bash ./dev_tools/scripts/sda/deploy-no-tls.sh pipeline
    - name: Wait for sda to become ready
      run: bash ./dev_tools/scripts/wait-for-pods.sh standalone_s3_svc_list
    - name: Run helm test
      run: bash ./dev_tools/scripts/run-helm-test.sh
