### Example file for running REMS using docker image from DockerHub
# See docs/installing-upgrading.md for more info

version: '2'
services:

  app:
    image: cscfi/rems:latest
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://db:5432/rems?user=rems&password=remspassword
      AUTHENTICATION: :fake
      PUBLIC_URL: http://localhost:3000/
    mem_reservation: 200m
    mem_limit: 2000m
    ports:
      - "127.0.0.1:3000:3000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rems
      POSTGRES_PASSWORD: remspassword
    mem_reservation: 30m
    mem_limit: 150m
    ports:
      - "127.0.0.1:5432:5432"
