### Example file for running REMS using a config file
# See docs/installing-upgrading.md for more info

version: '2'
services:

  app:
    image: cscfi/rems:latest
    mem_reservation: 200m
    mem_limit: 2000m
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./simple-config.edn:/rems/config/config.edn
      - ./example-theme/extra-styles.css:/rems/example-theme/extra-styles.css

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rems
      POSTGRES_PASSWORD: remspassword
    mem_reservation: 30m
    mem_limit: 150m
    ports:
      - "127.0.0.1:5432:5432"
