---
log:
  level: "info"
  format: "json"
elixir:
  id: "XC56EL11xx"
  provider: "http://oidc:9090"
  redirectUri: "http://oidc:31111/elixir/login"
  revocationUrl: "http://oidc:9090"
  secret: "wHPVQaYXmdDHg"
  jwkPath: "/jwks"
cega:
  authUrl: "http://cega:8443/username/"
  id: "dummy"
  secret: "dummy"
server:
  # do not use TLS until certs are fixed
  # cert: "keys/cert.pem"
  # key: "keys/key.pem"
s3Inbox: "s3.example.com"
jwtIssuer: "http://auth:8080"
jwtPrivateKey: "keys/sign-jwt.key"
jwtSignatureAlg: "ES256"
resignJwt: true
