version: '3.2'

# Environment variables here will override values in /config/config.ini

networks:
  net_registry:
    driver: bridge
  apps:
    driver: bridge
  other_net_registry:
    driver: bridge
services:

  # REGISTRY DB AND APP

  db_registry:
    hostname: db_registry
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: registry
    ports:
      - 5432
    volumes:
      - ./registry/db/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql:z
    networks:
      - net_registry

  app_registry:
    hostname: app_registry
    image: localhost:5000/beacon-network
    depends_on:
      - db_registry
    volumes: 
      - ./tests/test_files:/testconfig
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: 8083
      DB_HOST: db_registry
      DB_PORT: 5432
      BEACON_RUN_APP: registry
      DEBUG: "true"
      CONFIG_FILE: /testconfig/registry.ini
    links:
      - db_registry
    ports:
      - 8083:8083
    networks:
      - net_registry
      - apps

  # AGGREGATORAPP

  app_aggregator:
    hostname: app_aggregator
    image: localhost:5000/beacon-network
    volumes: 
      - ./tests/test_files:/testconfig
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: 5054
      BEACON_RUN_APP: aggregator
      DEBUG: "true"
      CONFIG_FILE: /testconfig/aggregator.ini
    ports:
      - 5054:5054
    networks:
      - apps

  other_db_registry:
    hostname: other_db_registry
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: registry
    ports:
      - 5433:5432
    volumes:
      - ./registry/db/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql:z
    networks:
      - other_net_registry

  other_registry:
    hostname: other_registry
    image: localhost:5000/beacon-network
    depends_on:
      - other_db_registry
    volumes: 
      - ./tests/test_files:/testconfig
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: 8082
      DB_HOST: other_db_registry
      DB_PORT: 5432
      BEACON_RUN_APP: registry
      DEBUG: "true"
      CONFIG_FILE: /testconfig/other_registry.ini
    links:
      - other_db_registry
    ports:
      - 8082:8082
    networks:
      - other_net_registry
      - apps

  # AGGREGATORAPP

  other_aggregator:
    hostname: other_aggregator
    image: localhost:5000/beacon-network
    volumes: 
      - ./tests/test_files:/testconfig
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: 5055
      BEACON_RUN_APP: aggregator
      DEBUG: "true"
      CONFIG_FILE: /testconfig/other_aggregator.ini
    ports:
      - 5055:5055
    networks:
      - apps

  bad_beacon:
    hostname: bad_beacon
    image: cscfi/beacon-python
    environment:
      HOST: "0.0.0.0"
      PORT: 5052
      DATABASE_URL: other_db_registry
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
      DATABASE_NAME: registry
    ports:
      - 5052:5052
    networks:
      - other_net_registry
      - apps
  
  extra_bad_beacon:
    hostname: extra_bad_beacon
    image: cscfi/beacon-python
    environment:
      HOST: "0.0.0.0"
      PORT: 5053
      DATABASE_URL: other_db_registry
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
      DATABASE_NAME: registry
    ports:
      - 5053:5053
    networks:
      - other_net_registry
      - apps

