apiVersion: v2
name: sda-orch
version: "0.7.5"
description: Orchestrate component for Sensitive Data Archive (SDA) standalone installation
home: https://neic-sda.readthedocs.io
icon: https://neic.no/assets/images/logo.png
sources:
- https://github.com/neicnordic/sda-helm
