{{- if not .Values.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-orchestrate
type: Opaque
data:
  mqPassword: {{ include "mqPass" . | b64enc }}
  {{- if .Values.datasetID.external }}
  dataciteKey: {{ required "DOI API key missing" .Values.datasetID.datacite.key | b64enc }}
  remsKey: {{ required "REMS API key missing" .Values.datasetID.rems.key | b64enc }}
  {{- end }}
{{- end }}
