{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if and (not .Values.global.vaultSecrets) .Values.global.tls.enabled }}
{{- if .Values.global.doa.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-doa
type: Opaque
data:
  dbPassword: {{ include "dbPassDoa" . | b64enc }}
{{- if and .Values.global.doa.outbox.enabled }}
  mqPassword: {{ include "mqPassDoa" . | b64enc }}
  mqUser: {{ include "mqUserDoa" . | b64enc }}
  {{- if eq "s3" .Values.global.doa.outbox.type }}
  s3OutboxAccessKey: {{ .Values.global.doa.outbox.s3AccessKey | quote | trimall "\"" | b64enc }}
  s3OutboxSecretKey: {{ .Values.global.doa.outbox.s3SecretKey | quote | trimall "\"" | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
