{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if .Values.global.download.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sda.fullname" . }}-download
  labels:
    app: {{ template "sda.fullname" . }}-download
spec:
  ports:
  - name: download
    port: {{ ternary 443 80 .Values.global.tls.enabled }}
    targetPort: download
    protocol: TCP
  selector:
    app: {{ template "sda.fullname" . }}-download
{{- end }}
{{- end }}
