{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if and .Values.global.download.enabled  (not .Values.global.vaultSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-download
type: Opaque
data:
  dbPassword: {{ include "dbPassDownload" . | b64enc }}
  c4ghPassphrase: {{ .Values.global.c4gh.passphrase | b64enc }}
  dbUser: {{ include "dbUserDownload" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-download-iss
type: Opaque
data:
  iss.json: {{ .Values.global.download.trusted.iss | toJson | b64enc | quote }}
{{- end }}
{{- end }}
