{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-mapper
type: Opaque
data:
  dbPassword: {{ include "dbPassMapper" . | b64enc }}
  dbUser: {{ include "dbUserMapper" . | b64enc }}
  mqPassword: {{ include "mqPassMapper" . | b64enc }}
  mqUser: {{ include "mqUserMapper" . | b64enc }}
{{- end }}
{{- end }}
