{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if eq "s3" .Values.global.inbox.storageType }}
{{- if not .Values.global.vaultSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-inbox
type: Opaque
data:
  dbPassword: {{ include "dbPassInbox" . | b64enc }}
  dbUser: {{ include "dbUserInbox" . | b64enc }}
  mqPassword: {{ include "mqPassInbox" . | b64enc }}
  s3InboxAccessKey: {{ .Values.global.inbox.s3AccessKey | b64enc }}
  s3InboxSecretKey: {{ .Values.global.inbox.s3SecretKey | b64enc }}
{{- end }}
{{- end }}
{{- end }}
