name: Publish version tag
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "**/README.md"
    types: [ closed ]

jobs:
  tag_release:
    if: github.event.pull_request.merged == true
    continue-on-error: true
    name: tag version
    outputs:
      part: ${{ steps.bump_tag.outputs.part }}
      tag: ${{ steps.bump_tag.outputs.tag }}
      new_tag: ${{ steps.bump_tag.outputs.new_tag }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: bump_tag
      uses: anothrNick/github-tag-action@1.66.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

  push_to_registry:
    needs: tag_release
    if: needs.tag_release.outputs.part != ''
    name: Push Docker image to Github Container registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull PR containers
        run : |
          for t in -auth -download -pipeline -postgres -rabbitmq -sftp-inbox; do
            docker pull ghcr.io/${{ github.repository }}:PR${{ github.event.number }}$t
          done
          docker pull ghcr.io/${{ github.repository }}:PR${{ github.event.number }}

      - name: Retag PR image for auth
        run: |
          docker tag ghcr.io/${{ github.repository }}:PR${{ github.event.number }}-auth ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}-auth
          docker push ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}-auth

      - name: Retag PR image for download
        run: |
          docker tag ghcr.io/${{ github.repository }}:PR${{ github.event.number }}-download ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}-download
          docker push ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}-download

      - name: Retag PR image for pipeline
        run: |
          docker tag ghcr.io/${{ github.repository }}:PR${{ github.event.number }}-pipeline ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}-pipeline
          docker push ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}-pipeline

      - name: Retag PR image for postgres
        run: |
          docker tag ghcr.io/${{ github.repository }}:PR${{ github.event.number }}-postgres ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}-postgres
          docker push ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}-postgres

      - name: Retag PR image for rabbitmq
        run: |
          docker tag ghcr.io/${{ github.repository }}:PR${{ github.event.number }}-rabbitmq ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}-rabbitmq
          docker push ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}-rabbitmq

      - name: Retag PR image for sftp-inbox
        run: |
          docker tag ghcr.io/${{ github.repository }}:PR${{ github.event.number }}-sftp-inbox ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}-sftp-inbox
          docker push ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}-sftp-inbox

      - name: Retag PR image for sensitive-data-archive
        run: |
          docker tag ghcr.io/${{ github.repository }}:PR${{ github.event.number }} ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}
          docker push ghcr.io/${{ github.repository }}:${{ needs.tag_release.outputs.tag }}
