name: Code tests

on:
  push:
    branches-ignore: [main]

jobs:

  sftp_inbox:
    strategy:
      matrix:
        java-version: [19]
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Test
        run: cd sda-sftp-inbox && mvn test -B

  test_pipeline:
    name: Test ingestion pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']
    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          cd sda-pipeline
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Create certificates
        run: |
          cd sda-pipeline/dev_utils
          bash ./make_certs.sh
          cd ..

      - name: Start MQ and DB
        run: |
          cd sda-pipeline
          docker-compose -f dev_utils/compose-no-tls.yml up -d db mq

      - name: Test
        run: |
          cd sda-pipeline
          go test --tags=integration -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./sda-pipeline/coverage.txt
          flags: unittests
          fail_ci_if_error: false

  test_download:
    name: Test Download
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']
    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          cd sda-download
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Test
        run: |
          cd sda-download
          go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./sda-download/coverage.txt
          flags: unittests
          fail_ci_if_error: false

  test_sda:
    name: Test sensitive-data-archive
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']
    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          cd sda-download
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Test
        run: |
          cd sda
          go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./sda/coverage.txt
          flags: unittests
          fail_ci_if_error: false
